ShopEzy/Controllers/CustomerUnitTestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Moq;
using NuGet.ContentModel;
using ShopEzy.Data;
using ShopEzy.Models;
using ShopEzy.utils;
using System.Net;
using Xunit;

namespace ShopEzy.Controllers
{
    public class CustomerUnitTestController : Controller
    {

        private static List<Customer> customerList = [];   

        public CustomerUnitTestController()
        {
            if (customerList.Count == 0) 
            {
                //create a list of customers
                customerList.Add(new Customer(1, "John", "Doe", "test1@email.com", "1234567890", DateTime.Now, "street", "1234567890"));
                customerList.Add(new Customer(2, "Jane", "Doe", "test2@email.com", "1234567890", DateTime.Now, "street", "1234567890"));
                customerList.Add(new Customer(3, "Bob", "Smith", "test3@email.com", "1234567890", DateTime.Now, "street", "1234567890"));
                customerList.Add(new Customer(4, "Alice", "Johnson", "test4@email.com", "1234567890", DateTime.Now, "street", "1234567890"));
            }
        }

        public IActionResult Index()
        {
            return View(customerList);
        }

        public IActionResult Login()
        {
            
            //get customer info
            var customer = customerList.FirstOrDefault();
            return View(customer);


        }

        public IActionResult Register()
        {
            //create a new customer
            Random random = new();
            Customer customer = new Customer();
            customer.Id = random.Next(1, 1000);
            customer.FirstName = "John"+ random.Next(1, 100);
            customer.LastName = "Doe" + random.Next(1, 100);
            customer.Email = "test" + random.Next(50, 100)+"@email.com";
            customer.PhoneNumber = "1234567890";
            customer.DateOfBirth = DateTime.Now;
            customer.Address = "street" + random.Next(1, 100);
            customer.Password = "1234567890";

            customerList.Add(customer);
            return View("Index", customerList);
        }


        [HttpGet]
        public IActionResult Update()
        {
            var customer = customerList.FirstOrDefault();
            return View(customer);

        }


        [HttpPost]
        public IActionResult Update(Customer customer)
        {
            var macthCustomer = customerList.FirstOrDefault(c => c.Id == customer.Id);
            if (macthCustomer == null)
            {
                return NotFound();
            }
            macthCustomer.FirstName = customer.FirstName;
            macthCustomer.LastName = customer.LastName;
            macthCustomer.PhoneNumber = customer.PhoneNumber;
            macthCustomer.DateOfBirth = customer.DateOfBirth;
            macthCustomer.Address = customer.Address;
            macthCustomer.Password = customer.Password;
            return View();

        }
    }
}

ShopEzy/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopEzy.Data;
using ShopEzy.Models;
using ShopEzy.utils;

namespace ShopEzy.Controllers
{
    public class ProductController : Controller
    {
        private readonly ShopEzyDbContext _context;

        // Constructor to inject the database context
        public ProductController(ShopEzyDbContext context)
        {
            _context = context;
        }

        // GET: Product
        /*public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }*/

        // GET: Product with sorting and searching
        public IActionResult Index(string sortOrder, string SearchName)
        {
            // Set the sort parameters for the view
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["CurrentFilter"] = SearchName;

            // Query all products
            var products = from p in _context.Product select p;

            // Apply search filter if provided
            if (!string.IsNullOrEmpty(SearchName))
            {
                products = products.Where(p => p.Name != null && p.Name.Contains(SearchName));
            }

            // Apply sorting based on the sortOrder parameter
            switch (sortOrder)
            {
                case "name_desc":
                    products = products.OrderByDescending(p => p.Name);
                    break;
                case "Price":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "price_desc":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderBy(p => p.Name);
                    break;
            }

            // Retrieve the customer from the session
            ViewBag.Customer = HttpContext.Session.GetObject<Customer>("customer");

            // Return the view with the filtered and sorted products
            return View(products.ToList());
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            // Return NotFound if id is null
            if (id == null)
            {
                return NotFound();
            }

            // Retrieve the product by id
            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);

            // Return NotFound if product is not found
            if (product == null)
            {
                return NotFound();
            }

            // Retrieve the customer from the session
            ViewBag.Customer = HttpContext.Session.GetObject<Customer>("customer");

            // Return the view with the product details
            return View(product);
        }
    }
}

ShopEzy/Controllers/ProductUnitTestController.cs
using Microsoft.AspNetCore.Mvc;
using ShopEzy.Models;

namespace ShopEzy.Controllers
{
    public class ProductUnitTestController : Controller
    {

        public List<Product> GetProductList() 
        {
            List<Product> productList = new List<Product>();
            Product product1 = new Product();
            product1.Id = 1;
            product1.Name = "Product 1";
            product1.Price = 500;
            product1.Description = "This is a test product 1";
            productList.Add(product1);
            Product product2 = new Product();
            product2.Id = 2;
            product2.Name = "Product 2";
            product2.Price = 100;
            product2.Description = "This is a test product 2";
            productList.Add(product2);
            Product product3 = new Product();
            product3.Id = 3;
            product3.Name = "Product 3";
            product3.Price = 400;
            product3.Description = "This is a test product 3";
            productList.Add(product3);  
            Product product4 = new Product();
            product4.Id = 4;
            product4.Name = "Product 4";
            product4.Price = 800;
            product4.Description = "This is a test product 4";
            productList.Add(product4);
            return productList;
        }

        public IActionResult Index()
        {
            List<Product> productList = GetProductList();
            return View(productList);
        }

        public IActionResult Details(int id)
        {
            var product = GetProductList().FirstOrDefault(p => p.Id == id);

            return View(product);
        }


        public IActionResult SearchName()
        {
            List<Product> productList = GetProductList();
            var result = productList.Where(p => p.Name != null && p.Name.Contains("1"));

            return View("Index", result);
        }

        public IActionResult SortByName()
        {
            List<Product> productList = GetProductList();
            var result = productList.OrderByDescending(p => p.Name);

            return View("Index", result);
        }

        public IActionResult SortByPrice()
        {
            List<Product> productList = GetProductList();
            var result = productList.OrderByDescending(p => p.Price);

            return View("Index", result);
        }


    }
}

ShopEzy/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Castle.Core.Resource;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopEzy.Data;
using ShopEzy.Models;
using ShopEzy.utils;

namespace ShopEzy.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ShopEzyDbContext _context;

        public TransactionController(ShopEzyDbContext context)
        {
            _context = context;
        }

        // GET: Transaction
        public async Task<IActionResult> Index()
        {
            var customer = HttpContext.Session.GetObject<Customer>("customer");
            if (customer == null)
            {
                TempData["ErrorMessage"] = "You have not Login!";
                return RedirectToAction("Login", "Customer");
            }
            var transactions = await _context.Transaction
                 .Where(t => t.CustomerId == customer.Id)
                 .ToListAsync();

            if (!transactions.Any())
            {
                TempData["ErrorMessage"] = "You have not Purchase Anything!";
                return RedirectToAction("Index", "Product");
            }
            // Retrieve the customer from the session
            ViewBag.Customer = HttpContext.Session.GetObject<Customer>("customer");
            return View(transactions);
        }




        // POST: Transaction/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(string name,decimal price, int Id)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            //get customer info 
            var customer = HttpContext.Session.GetObject<Customer>("customer");
            if (customer == null) 
            {
                TempData["ErrorMessage"] = "You have not Login!";
                ModelState.AddModelError("", "You have not Login!");
                return RedirectToAction("Login", "Customer");
            }
            //create a new transaction object
            Transaction transaction = new Transaction();
            transaction.CustomerId = customer.Id;
            transaction.ProductId = Id;
            transaction.ProductName = name;
            transaction.Quantity = 1;
            transaction.Price = price;
            transaction.Date = DateTime.Now;
            // add a new record into database
            _context.Add(transaction);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // POST: Transaction/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            //get customer info 
            var customer = HttpContext.Session.GetObject<Customer>("customer");
            if (customer == null)
            {
                TempData["ErrorMessage"] = "You have not Login!";
                ModelState.AddModelError("", "You have not Login!");
                return RedirectToAction("Login", "Customer");
            }
            var transaction = await _context.Transaction
                .FirstOrDefaultAsync(t => t.Id == id && t.CustomerId == customer.Id);
            if (transaction != null)
            {
                _context.Transaction.Remove(transaction);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

ShopEzy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopEzy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopEzy.styles.css" asp-append-version="true" />
    <style>
        body {
            background-image: url('/images/bg1.jpg'); 
            background-size: cover; 
            background-repeat: no-repeat; 
            background-position: -250px center;
        }


    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">ShopEzy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerUnitTest" asp-action="Index">Customer Unit Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductUnitTest" asp-action="Index">Product Unit Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransactionUnitTest" asp-action="Index">Transaction Unit Test</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">

                        @if (ViewBag.Customer != null)
                        {

                            <a id="cusomterDetails" class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">
                                <span>Welcome, @ViewBag.Customer.FirstName</span> |
                            </a>
                            <li class="nav-item">
                                <a id="viewTransaction" class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transaction History</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a id="loginLink" class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ShopEzy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>